server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  tracing:
    sampling:
      probability: 1.0